image: eclipse-temurin:8

variables:
  GRADLE_ARGS: --no-daemon --stacktrace --warning-mode=all
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  paths:
    - .gradle/caches
    - .gradle/notifications
    - .gradle/wrapper

tests:
  stage: test
  script: ./gradlew ${GRADLE_ARGS} check
  artifacts:
    paths:
      - "*/build/reports"
      - "*/build/test-results"
    reports:
      junit:
        - "*/build/test-results/**/TEST-*.xml"
    when: always

publish:
  stage: deploy
  script:
    - openssl aes-256-cbc -pass "env:ENCRYPTION_PASSWORD" -in secring.gpg.enc -out secring.gpg -d
    - openssl aes-256-cbc -pass "env:ENCRYPTION_PASSWORD" -in pubring.gpg.enc -out pubring.gpg -d
    - openssl aes-256-cbc -pass "env:ENCRYPTION_PASSWORD" -in gradle.properties.enc -out gradle.properties -d
    - ./gradlew ${GRADLE_ARGS} uploadArchives
  only:
    - master@general/stups/probkodkod
